import { Party, Question } from './types';

export const questions: Question[] = [
  // --- WIRTSCHAFT & ARBEIT ---
  {
    id: 'q1',
    text: 'Der Bürokratieabbau für Unternehmen soll oberste Priorität der Landespolitik sein.',
    category: 'Wirtschaft',
  },
  {
    id: 'q2',
    text: 'Öffentliche Aufträge sollen nur an tarifgebundene Unternehmen vergeben werden.',
    category: 'Wirtschaft',
  },
  {
    id: 'q3',
    text: 'Das Land soll einen eigenen Staatsfonds oder Zukunftsfonds zur Wirtschaftsförderung auflegen.',
    category: 'Wirtschaft',
  },
  {
    id: 'q4',
    text: 'Die Meisterausbildung im Handwerk soll komplett gebührenfrei werden.',
    category: 'Wirtschaft',
  },
  {
    id: 'q5',
    text: 'Baden-Württemberg soll als Rüstungsstandort aktiv gestärkt werden.',
    category: 'Wirtschaft',
  },
  // --- AUTOMOBILINDUSTRIE ---
  {
    id: 'q6',
    text: 'Das EU-Verbrennerverbot ab 2035 soll aufgehoben werden.',
    category: 'Automobilindustrie',
  },
  {
    id: 'q7',
    text: 'Baden-Württemberg soll konsequent auf Elektromobilität als Antrieb der Zukunft setzen.',
    category: 'Automobilindustrie',
  },
  {
    id: 'q8',
    text: 'Synthetische Kraftstoffe (E-Fuels) sollen als gleichwertige Alternative zum E-Auto gefördert werden.',
    category: 'Automobilindustrie',
  },
  {
    id: 'q9',
    text: 'Die Automobilzulieferer sollen bei der Transformation finanziell stärker vom Land unterstützt werden.',
    category: 'Automobilindustrie',
  },
  // --- ENERGIE ---
  {
    id: 'q10',
    text: 'Der Ausbau von Windkraftanlagen in Baden-Württemberg soll beschleunigt werden.',
    category: 'Energie',
  },
  {
    id: 'q11',
    text: 'Es soll eine Solarpflicht für alle Neubauten geben.',
    category: 'Energie',
  },
  {
    id: 'q12',
    text: 'Das Erneuerbare-Wärme-Gesetz des Landes soll abgeschafft werden.',
    category: 'Energie',
  },
  {
    id: 'q13',
    text: 'Die Forschung an Kernfusion und neuen Nukleartechnologien soll gefördert werden.',
    category: 'Energie',
  },
  {
    id: 'q14',
    text: 'Energiepreise müssen durch alle verfügbaren Mittel gesenkt werden, auch wenn das Klimaziele verzögert.',
    category: 'Energie',
  },
  // --- KLIMASCHUTZ ---
  {
    id: 'q15',
    text: 'Baden-Württemberg soll bis 2040 klimaneutral werden (statt des EU-Ziels 2050).',
    category: 'Klimaschutz',
  },
  {
    id: 'q16',
    text: 'Klimaschutz soll primär über den europäischen Emissionshandel geregelt werden statt durch Landesgesetze.',
    category: 'Klimaschutz',
  },
  {
    id: 'q17',
    text: 'GreenTech und Umwelttechnologien sollen als Wachstumsbranche gezielt gefördert werden.',
    category: 'Klimaschutz',
  },
  // --- BILDUNG ---
  {
    id: 'q18',
    text: 'Eine verbindliche Grundschulempfehlung soll wieder eingeführt werden.',
    category: 'Bildung',
  },
  {
    id: 'q19',
    text: 'Das neunjährige Gymnasium (G9) ist der richtige Weg.',
    category: 'Bildung',
  },
  {
    id: 'q20',
    text: 'Alle Kita-Plätze sollen komplett gebührenfrei sein.',
    category: 'Bildung',
  },
  {
    id: 'q21',
    text: 'Das gegliederte Schulsystem (Gymnasium, Realschule, Hauptschule) soll beibehalten werden.',
    category: 'Bildung',
  },
  {
    id: 'q22',
    text: 'Die Gemeinschaftsschule soll als gleichwertige Schulform weiter ausgebaut werden.',
    category: 'Bildung',
  },
  {
    id: 'q23',
    text: 'Alle Kinder sollen vor der Einschulung ausreichende Deutschkenntnisse nachweisen müssen.',
    category: 'Bildung',
  },
  {
    id: 'q24',
    text: 'Das letzte Kindergartenjahr soll für alle Kinder verpflichtend sein.',
    category: 'Bildung',
  },
  {
    id: 'q25',
    text: 'Smartphones sollen an Grundschulen verboten werden.',
    category: 'Bildung',
  },
  // --- WOHNEN ---
  {
    id: 'q26',
    text: 'Das Land soll eine eigene Wohnungsbaugesellschaft gründen, um selbst bezahlbaren Wohnraum zu schaffen.',
    category: 'Wohnen',
  },
  {
    id: 'q27',
    text: 'Die Mietpreisbremse soll verschärft und auf mehr Kommunen ausgeweitet werden.',
    category: 'Wohnen',
  },
  {
    id: 'q28',
    text: 'Die Grunderwerbsteuer soll beim Kauf der ersten eigenen Immobilie gesenkt oder abgeschafft werden.',
    category: 'Wohnen',
  },
  {
    id: 'q29',
    text: 'Sozialer Wohnungsbau mit langer Mietpreisbindung soll massiv ausgebaut werden.',
    category: 'Wohnen',
  },
  // --- MOBILITÄT ---
  {
    id: 'q30',
    text: 'Der ÖPNV soll massiv ausgebaut und das Deutschlandticket beibehalten werden.',
    category: 'Mobilität',
  },
  {
    id: 'q31',
    text: 'Neue Autobahnen und Bundesstraßen sollen weiterhin gebaut und ausgebaut werden.',
    category: 'Mobilität',
  },
  {
    id: 'q32',
    text: 'Radwege und Radschnellwege sollen deutlich stärker ausgebaut werden.',
    category: 'Mobilität',
  },
  {
    id: 'q33',
    text: 'Für Menschen mit geringem Einkommen soll der ÖPNV kostenlos sein.',
    category: 'Mobilität',
  },
  // --- INNERE SICHERHEIT ---
  {
    id: 'q34',
    text: 'Die Polizei soll deutlich mehr Personal bekommen.',
    category: 'Innere Sicherheit',
  },
  {
    id: 'q35',
    text: 'Videoüberwachung an Bahnhöfen und öffentlichen Plätzen soll ausgebaut werden.',
    category: 'Innere Sicherheit',
  },
  {
    id: 'q36',
    text: 'Es soll eine konsequente Null-Toleranz-Strategie bei Gewaltkriminalität gelten.',
    category: 'Innere Sicherheit',
  },
  // --- MIGRATION & INTEGRATION ---
  {
    id: 'q37',
    text: 'Abschiebungen abgelehnter Asylbewerber sollen konsequenter durchgesetzt werden.',
    category: 'Migration',
  },
  {
    id: 'q38',
    text: 'Die Zuwanderung von ausländischen Fachkräften soll erleichtert werden.',
    category: 'Migration',
  },
  {
    id: 'q39',
    text: 'Sozialleistungen für Asylbewerber sollen komplett auf Sachleistungen umgestellt werden.',
    category: 'Migration',
  },
  {
    id: 'q40',
    text: 'Die Zuwanderung nach Deutschland soll generell deutlich stärker begrenzt werden.',
    category: 'Migration',
  },
  // --- DEMOKRATIE & GESELLSCHAFT ---
  {
    id: 'q41',
    text: 'Das Wahlalter bei Landtagswahlen soll auf 16 Jahre gesenkt werden.',
    category: 'Demokratie',
  },
  {
    id: 'q42',
    text: 'Volksentscheide auf Landesebene sollen erleichtert werden.',
    category: 'Demokratie',
  },
  {
    id: 'q43',
    text: 'Die Gleichstellung und der Schutz von LGBTQ+-Personen soll aktiv gefördert werden.',
    category: 'Gesellschaft',
  },
  // --- FINANZEN ---
  {
    id: 'q44',
    text: 'Die Schuldenbremse soll strikt eingehalten werden – auch wenn Investitionen zurückgestellt werden müssen.',
    category: 'Finanzen',
  },
  {
    id: 'q45',
    text: 'Das Land soll neue Schulden aufnehmen dürfen, um in Infrastruktur (Straßen, Schulen, Digitales) zu investieren.',
    category: 'Finanzen',
  },
  // --- GESUNDHEIT ---
  {
    id: 'q46',
    text: 'Krankenhäuser sollen in öffentlicher Hand bleiben und nicht privatisiert werden.',
    category: 'Gesundheit',
  },
  {
    id: 'q47',
    text: 'Im ländlichen Raum sollen mehr Gesundheitszentren entstehen, um die Versorgung zu sichern.',
    category: 'Gesundheit',
  },
  // --- AUSSEN- UND FRIEDENSPOLITIK ---
  {
    id: 'q48',
    text: 'Deutschland soll die Ukraine weiterhin militärisch unterstützen.',
    category: 'Außenpolitik',
  },
  {
    id: 'q49',
    text: 'Die Ausgaben für Verteidigung und Bundeswehr sollen deutlich erhöht werden.',
    category: 'Außenpolitik',
  },
  // --- LANDWIRTSCHAFT ---
  {
    id: 'q50',
    text: 'Die ökologische Landwirtschaft soll stärker gefördert werden als die konventionelle.',
    category: 'Landwirtschaft',
  },
];

export const parties: Party[] = [
  {
    id: 'gruene',
    name: 'GRÜNE',
    longName: 'Bündnis 90/Die Grünen Baden-Württemberg',
    color: '#46962b',
    positions: {
      q1: 'agree',
      q2: 'agree',
      q3: 'neutral',
      q4: 'agree',
      q5: 'disagree',
      q6: 'disagree',
      q7: 'agree',
      q8: 'disagree',
      q9: 'agree',
      q10: 'agree',
      q11: 'agree',
      q12: 'disagree',
      q13: 'neutral',
      q14: 'disagree',
      q15: 'agree',
      q16: 'disagree',
      q17: 'agree',
      q18: 'disagree',
      q19: 'agree',
      q20: 'neutral',
      q21: 'neutral',
      q22: 'agree',
      q23: 'agree',
      q24: 'agree',
      q25: 'neutral',
      q26: 'neutral',
      q27: 'agree',
      q28: 'neutral',
      q29: 'agree',
      q30: 'agree',
      q31: 'disagree',
      q32: 'agree',
      q33: 'neutral',
      q34: 'agree',
      q35: 'neutral',
      q36: 'neutral',
      q37: 'neutral',
      q38: 'agree',
      q39: 'disagree',
      q40: 'disagree',
      q41: 'agree',
      q42: 'agree',
      q43: 'agree',
      q44: 'neutral',
      q45: 'agree',
      q46: 'agree',
      q47: 'agree',
      q48: 'agree',
      q49: 'neutral',
      q50: 'agree',
    },
  },
  {
    id: 'cdu',
    name: 'CDU',
    longName: 'CDU Baden-Württemberg',
    color: '#000000',
    positions: {
      q1: 'agree',
      q2: 'neutral',
      q3: 'agree',
      q4: 'agree',
      q5: 'agree',
      q6: 'agree',
      q7: 'disagree',
      q8: 'agree',
      q9: 'agree',
      q10: 'neutral',
      q11: 'neutral',
      q12: 'agree',
      q13: 'agree',
      q14: 'neutral',
      q15: 'disagree',
      q16: 'agree',
      q17: 'agree',
      q18: 'agree',
      q19: 'agree',
      q20: 'neutral',
      q21: 'agree',
      q22: 'neutral',
      q23: 'agree',
      q24: 'agree',
      q25: 'neutral',
      q26: 'neutral',
      q27: 'neutral',
      q28: 'agree',
      q29: 'agree',
      q30: 'agree',
      q31: 'agree',
      q32: 'agree',
      q33: 'neutral',
      q34: 'agree',
      q35: 'agree',
      q36: 'agree',
      q37: 'agree',
      q38: 'agree',
      q39: 'neutral',
      q40: 'neutral',
      q41: 'disagree',
      q42: 'neutral',
      q43: 'neutral',
      q44: 'agree',
      q45: 'disagree',
      q46: 'neutral',
      q47: 'agree',
      q48: 'agree',
      q49: 'agree',
      q50: 'neutral',
    },
  },
  {
    id: 'spd',
    name: 'SPD',
    longName: 'SPD Baden-Württemberg',
    color: '#e3000f',
    positions: {
      q1: 'agree',
      q2: 'agree',
      q3: 'agree',
      q4: 'agree',
      q5: 'neutral',
      q6: 'disagree',
      q7: 'agree',
      q8: 'neutral',
      q9: 'agree',
      q10: 'agree',
      q11: 'agree',
      q12: 'disagree',
      q13: 'neutral',
      q14: 'disagree',
      q15: 'agree',
      q16: 'disagree',
      q17: 'agree',
      q18: 'disagree',
      q19: 'agree',
      q20: 'agree',
      q21: 'disagree',
      q22: 'agree',
      q23: 'agree',
      q24: 'agree',
      q25: 'agree',
      q26: 'agree',
      q27: 'agree',
      q28: 'agree',
      q29: 'agree',
      q30: 'agree',
      q31: 'neutral',
      q32: 'agree',
      q33: 'neutral',
      q34: 'agree',
      q35: 'neutral',
      q36: 'neutral',
      q37: 'neutral',
      q38: 'agree',
      q39: 'disagree',
      q40: 'disagree',
      q41: 'agree',
      q42: 'agree',
      q43: 'agree',
      q44: 'disagree',
      q45: 'agree',
      q46: 'agree',
      q47: 'agree',
      q48: 'agree',
      q49: 'neutral',
      q50: 'agree',
    },
  },
  {
    id: 'fdp',
    name: 'FDP',
    longName: 'FDP Baden-Württemberg',
    color: '#ffcc00',
    positions: {
      q1: 'agree',
      q2: 'disagree',
      q3: 'neutral',
      q4: 'agree',
      q5: 'neutral',
      q6: 'agree',
      q7: 'disagree',
      q8: 'agree',
      q9: 'neutral',
      q10: 'neutral',
      q11: 'disagree',
      q12: 'agree',
      q13: 'agree',
      q14: 'agree',
      q15: 'disagree',
      q16: 'agree',
      q17: 'neutral',
      q18: 'neutral',
      q19: 'agree',
      q20: 'neutral',
      q21: 'agree',
      q22: 'neutral',
      q23: 'agree',
      q24: 'neutral',
      q25: 'neutral',
      q26: 'disagree',
      q27: 'disagree',
      q28: 'agree',
      q29: 'neutral',
      q30: 'agree',
      q31: 'agree',
      q32: 'neutral',
      q33: 'disagree',
      q34: 'agree',
      q35: 'neutral',
      q36: 'agree',
      q37: 'agree',
      q38: 'agree',
      q39: 'neutral',
      q40: 'neutral',
      q41: 'agree',
      q42: 'agree',
      q43: 'agree',
      q44: 'agree',
      q45: 'disagree',
      q46: 'neutral',
      q47: 'agree',
      q48: 'agree',
      q49: 'agree',
      q50: 'disagree',
    },
  },
  {
    id: 'afd',
    name: 'AfD',
    longName: 'Alternative für Deutschland Baden-Württemberg',
    color: '#009ee0',
    positions: {
      q1: 'agree',
      q2: 'disagree',
      q3: 'agree',
      q4: 'neutral',
      q5: 'neutral',
      q6: 'agree',
      q7: 'disagree',
      q8: 'agree',
      q9: 'neutral',
      q10: 'disagree',
      q11: 'disagree',
      q12: 'agree',
      q13: 'agree',
      q14: 'agree',
      q15: 'disagree',
      q16: 'neutral',
      q17: 'disagree',
      q18: 'agree',
      q19: 'agree',
      q20: 'agree',
      q21: 'agree',
      q22: 'disagree',
      q23: 'agree',
      q24: 'neutral',
      q25: 'neutral',
      q26: 'disagree',
      q27: 'disagree',
      q28: 'agree',
      q29: 'neutral',
      q30: 'neutral',
      q31: 'agree',
      q32: 'disagree',
      q33: 'disagree',
      q34: 'agree',
      q35: 'neutral',
      q36: 'agree',
      q37: 'agree',
      q38: 'disagree',
      q39: 'agree',
      q40: 'agree',
      q41: 'disagree',
      q42: 'agree',
      q43: 'disagree',
      q44: 'agree',
      q45: 'disagree',
      q46: 'agree',
      q47: 'neutral',
      q48: 'disagree',
      q49: 'neutral',
      q50: 'disagree',
    },
  },
  {
    id: 'fw',
    name: 'FW',
    longName: 'Freie Wähler Baden-Württemberg',
    color: '#f29400',
    positions: {
      q1: 'agree',
      q2: 'neutral',
      q3: 'neutral',
      q4: 'agree',
      q5: 'neutral',
      q6: 'neutral',
      q7: 'neutral',
      q8: 'agree',
      q9: 'agree',
      q10: 'neutral',
      q11: 'neutral',
      q12: 'neutral',
      q13: 'neutral',
      q14: 'neutral',
      q15: 'neutral',
      q16: 'neutral',
      q17: 'agree',
      q18: 'disagree',
      q19: 'agree',
      q20: 'agree',
      q21: 'agree',
      q22: 'agree',
      q23: 'agree',
      q24: 'agree',
      q25: 'neutral',
      q26: 'neutral',
      q27: 'neutral',
      q28: 'neutral',
      q29: 'agree',
      q30: 'agree',
      q31: 'agree',
      q32: 'neutral',
      q33: 'agree',
      q34: 'agree',
      q35: 'neutral',
      q36: 'agree',
      q37: 'agree',
      q38: 'agree',
      q39: 'neutral',
      q40: 'neutral',
      q41: 'neutral',
      q42: 'agree',
      q43: 'neutral',
      q44: 'neutral',
      q45: 'neutral',
      q46: 'neutral',
      q47: 'agree',
      q48: 'neutral',
      q49: 'neutral',
      q50: 'neutral',
    },
  },
  {
    id: 'bsw',
    name: 'BSW',
    longName: 'Bündnis Sahra Wagenknecht Baden-Württemberg',
    color: '#731e42',
    positions: {
      q1: 'agree',
      q2: 'agree',
      q3: 'neutral',
      q4: 'agree',
      q5: 'disagree',
      q6: 'agree',
      q7: 'disagree',
      q8: 'neutral',
      q9: 'agree',
      q10: 'neutral',
      q11: 'neutral',
      q12: 'neutral',
      q13: 'disagree',
      q14: 'agree',
      q15: 'neutral',
      q16: 'neutral',
      q17: 'neutral',
      q18: 'neutral',
      q19: 'agree',
      q20: 'agree',
      q21: 'neutral',
      q22: 'neutral',
      q23: 'agree',
      q24: 'agree',
      q25: 'agree',
      q26: 'neutral',
      q27: 'agree',
      q28: 'neutral',
      q29: 'agree',
      q30: 'agree',
      q31: 'neutral',
      q32: 'agree',
      q33: 'agree',
      q34: 'agree',
      q35: 'disagree',
      q36: 'agree',
      q37: 'agree',
      q38: 'neutral',
      q39: 'neutral',
      q40: 'agree',
      q41: 'neutral',
      q42: 'agree',
      q43: 'neutral',
      q44: 'neutral',
      q45: 'neutral',
      q46: 'agree',
      q47: 'agree',
      q48: 'disagree',
      q49: 'disagree',
      q50: 'agree',
    },
  },
  {
    id: 'linke',
    name: 'LINKE',
    longName: 'Die Linke Baden-Württemberg',
    color: '#be3075',
    positions: {
      q1: 'neutral',
      q2: 'agree',
      q3: 'neutral',
      q4: 'agree',
      q5: 'disagree',
      q6: 'disagree',
      q7: 'agree',
      q8: 'disagree',
      q9: 'agree',
      q10: 'agree',
      q11: 'agree',
      q12: 'disagree',
      q13: 'disagree',
      q14: 'disagree',
      q15: 'agree',
      q16: 'disagree',
      q17: 'agree',
      q18: 'disagree',
      q19: 'agree',
      q20: 'agree',
      q21: 'disagree',
      q22: 'agree',
      q23: 'neutral',
      q24: 'agree',
      q25: 'neutral',
      q26: 'agree',
      q27: 'agree',
      q28: 'disagree',
      q29: 'agree',
      q30: 'agree',
      q31: 'disagree',
      q32: 'agree',
      q33: 'agree',
      q34: 'neutral',
      q35: 'disagree',
      q36: 'disagree',
      q37: 'disagree',
      q38: 'agree',
      q39: 'disagree',
      q40: 'disagree',
      q41: 'agree',
      q42: 'agree',
      q43: 'agree',
      q44: 'disagree',
      q45: 'agree',
      q46: 'agree',
      q47: 'agree',
      q48: 'disagree',
      q49: 'disagree',
      q50: 'agree',
    },
  },
];
